 %% بسم الله الرحمن الرحیم 

%% ## Clear Waste Variables ##
% 07.01.2021, Ferhat Yılmaz

%% Description
%{
	Script to clear waste variables.
%}

%%
% Clear PATH variables
clear PATH_applianceData...
			PATH_defaultValues...
			PATH_geneticAlgorithm...
			PATH_initialConditions...
			PATH_residentalTypes...
			PATH_runprobabilityParameters

% Clear demand data variables
clear COUNT_WEEKS...
			DAY_PIECE...
			SAMPLE_PERIOD...
			GLOB_MAX_OPERATION_LIMIT...
			COUNT_SAMPLE_IN_DAY...

% Clear genetic algorithm core variables
clear RAND_METHOD...
			CROSSOVER_METHODS...
			COUNT_CHROMOSOMES...
			COUNT_GENES...
			GENE_LOW_LIMIT...
			GENE_UP_LIMIT...
			TERMINATION_ERROR_PERCENTAGE...
			TERMINATION_CHROMOSOME_COUNT...
			COUNT_CHOSENS...
			COUNT_ELITES...
			COUNT_OFFSPRINGS

% Clear genetic algorithm mutation variables
clear MUTATION_CHROMOSOME_PERCENT...
			MUTANT_CHROMOSOME_EFFECT...
			MUTATION_GENE_PERCENT...
			MUTANT_GENE_EFFECT...
			MUTATION_RATE
		
% Clear other variables
clear msg...
			fmt_bestChromosome...
			fmt_topfitnessValues...
			endUserType...
			applianceName...
			endUser_idx...
			parameter_idx...
			parameterArray...
			appliancesName
